### ISSUE TITLE
 Permalink only to display when hoover over it.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#102]
One other thing which might be helpful is to get the Permalink to display only when one hoovers over it like python or github uses it.

![untitled1](https://cloud.githubusercontent.com/assets/6168860/7453146/99c69702-f23c-11e4-9076-c350a19ff74f.png)
![untitled2](https://cloud.githubusercontent.com/assets/6168860/7453148/9b8661bc-f23c-11e4-9d14-58b1c6f558cc.png)

**Comment by MichaelHatherly** [comment]
That would be nice. :+1:

**Comment by peter1000** [comment]
I spend a little time on the new MkDocs version: it does support this out of the box for headers.

- seems it would require that also: obj definitions must be a header. **remove()** would not do it.

- the link is a long name e.g. for

```julia
parsedocs(::Docile.Formats.Format{F<:Docile.Formats.AbstractFormatter}, raw, mod, obj) 
```

one gets: `#parsedocsdocileformatsformatfdocileformatsabstractformatter-raw-mod-obj`


---

ADVANTAGE:

- works out of the box by adding: to the `mkdocs.yml`

```
markdown_extensions:
    - toc:
        permalink: ""
```

- no extra anchor needed to be added: which should make it also easier for other themes with top banner

  by the way: all themes except `mkdocs` and `readthedocs` will be removed from the main mkdocs package [here](https://github.com/mkdocs/mkdocs/issues/201)

- for the index one would only need to produce the same long reference links as mkdocs.

DISADVANTAGE:

- github source pages would not have the hyperlink anymore [like this](https://github.com/MichaelHatherly/Docile.jl/blob/master/docs/api/Docile.Cache.md#method__getparsed.2)

  not sure how important that is?

- only headers are supported: that is maybe an issue as some might want to only use **bold** for individual object signatures.

  header 4, 5 or 6 might be also ok instead?

- for other formats or markdown renderer one would need to write the anchors 

  for other formats one might want to write them anyway or not even have those anchors and permalink?

  other markdown renderer?   [MkDocs had about 33178 downloads in the last month ] (https://pypi.python.org/pypi/mkdocs)

----

Seems a nice option out of the box: hooverable permalinks - only produce same link references for index page !! but works only for mkdocs?

**Comment by peter1000** [comment]
In the new Docile (julia 0.4/0.5) not anymore relevant.
