### ISSUE TITLE
Propose new `section` meta.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#103]
This idea might be really worhty to consider (in my opinion at least).

It follows from this ( Respect the :section metadata when generating help HTML #8 )

---

**Reworked output system for new Lexicon**

Currently we use a number of different config setting to handle this.

[Config](http://lexiconjl.readthedocs.org/en/latest/api/Lexicon/#type__config.1)

* `category_order` Categories to include in the output in the defined order.
* `include_internal` To exclude documentation for non-exported objects, the keyword argument include_internal = false should be set. This is only supported for markdown.
* `md_subheader`

   * md_subheader=:simple adds documentation and API-Index subheaders "Exported" / "Internal".
   * md_subheader=:category adds documentation and API-Index subheaders per category.
   * md_subheader=:skip adds no subheaders to the documentation and API-Index and can be used for documentation which has only few entries.

---

Currently we have a structure like this

outputfile.md
    
    - Page Header: ModuleName
    - Header1: Exported

        - Section1: :methods
        
            * obj1()
            
            * obj2()
        
        - Section2: :types
        
            * obj1()
            
            * obj2()
    
    - Header2: Internal

        - Section1: :methods
        
            * obj1()
            
            * obj2()
        
        - Section2: :types
        
            * obj1()
            
            * obj2()

This info is also internaly available.

---

Until now most Lexicon user did think of saving documentation per `module`. 

With the *New Docile* we can think about saving documentation for `packages` or even for `a whole list of packages` and intermix them. 

So why don't we combine all of that in a much more flexible system.

---

1. `:pages` this is the final output page: whatever mixture of content it gets: does not mean only from one module
nor only one package - it could get all types from 5 packages or any other mixture of object documentation.

pages can contain optional:

* Any number of Headers

Headers can contain optional:

* Any number of SectionHeaders
* documentation

SectionHeaders can container

* documentation
   
---

documentation item order is by simple incrementation

---

To make the reference to the place easy all is handled similar to a file path.

A documentations final output position can be defined like this:
 
CASE 1: I want to place a new `aside` note in the PageHeader (Module: Lexicon) of file Lexicon.md

```
["""
This is a new idea the first item below the PageHeader.

:page=Lexicon.md/Module: Lexicon/1
"""]
```

CASE 2: I want to place a function's docstring into file ConvertFunctions.md under a Header(Unicode) in the Section (Asia) as the 6 item

```
"""
My new convert unicode japanese function
"""
function jp_unicode_convert()
end

:page=ConvertFunctions.md/Unicode/Asia/6
"""
```

For automatic api like now we could internally create the sections like we use it now

One could also go the whole way and allow sub sub sections maybe 6 like there are header # but I'm not sure if I would go that way.

Also one would need to see how this could finally be implemented but I find the idea quite convincing.

Want to move the above `jp_unicode_convert` to an other page.

just replace the :page meta with

`:page=Asia.md/Unicode/ConvertFunctions/23`

---

**Shortcoming:**

The above is quite nice but does not allow for moving whole Sections easily because the whole path is hard coded and would need to be changed each docstring.

* Advantage because the whole path is always given one can do probably a string replace.

* maybe one could do something like on the filesystem: move directory or so ;)

Aside of the shortcoming this might be a real good thing and is probably doable keeping our automatic asignments to "Exported/Internal" Headers with "Sections by Category"

the `:page` meta would replace any old `:section` tags.

**Comment by MichaelHatherly** [comment]
This sounds good. Getting a nice user-friendly way to specify things will definitely be needed, but I'd be happy with adding something like this, or that achieves the same goal at least.

**Comment by peter1000** [comment]
My Idea would be that `save` does not specify the file path anymore but an output dir.

This would allow the document writer to specify a whole structure without package name clashes when 2 pkg provide the same page.md name or if one wants to have the final output in an subfolder.

---

For all objects which do not provide a `:page meta` we could *fall back* to the current options:

* page path: modulename.md
* Module Header: ModuleName: providing a placeholder `:modname`
* Headers: Exported, Internal
* Sections: Categories: providing a convinence placeholder `:all` 
* objects: order like now

in Config have one option to define which autostructure is wanted by defining Headers and Sections all optional a Vector with tuples: Header [Sections]

e.g.  The below would be the same as what we use now but include_internal=false

```
pages = [(:modname, []),  (:Exported, [:all])]
```
Internal we produce `:page` metas: 

```
:page=Lexicon.md/Exported/methods/1
:page=Lexicon.md/Exported/methods/2

:page=Lexicon.md/Exported/types/1
:page=Lexicon.md/Exported/types/2
```
---

To put docstrings wihtout a :page meta including only Internal methods first and Exported methos, macros

```
pages = [(:modname, []), (:Internal, [:methods]),  (:Exported, [:methos, :macros])]
```

We gould probably do most work with the path methods provided by julia.

`:page=Lexicon.md/Exported/types/2`  

* basename(:page)  - '1'
* dirname(page) - is the Section path where to put it: 'Lexicon.md/Exported/types'

anyway if you think something like that is worthy this could superceed issue: https://github.com/MichaelHatherly/Lexicon.jl/issues/8

**Comment by peter1000** [comment]
If it is fine with you I would like to start with some code for this:

* Extraction of the `:page` meta content from the `getraw` txt.
* adding the meta `:page` to the getmeta[obj]
  - if no `:page` was defined add an calulated one based on Modulename/Exported/Internal Category settings

* Implement the part so that the obj docstrings are actuelly written to the right output page/Header/Section in the defined order

  * None defined items in sorted order others as defined in the `:page` meta

I think I'm able to do this and then come back to you for a review and maybe code improvement?

**What do you say?**

**Comment by MichaelHatherly** [comment]
> Extraction of the :page meta content from the getraw txt.

We will need to have a *general* metadata extraction facility setup first before we can start working on this I'd think.

Other than that the proposal seems worth trying out.

**Comment by peter1000** [comment]
I thought because in general `metadata` are expected at the end of an docstring to use something simple on the rawtxt.

e.g.
```
startidx = rsearchindex(txt, ":page")
if startidx > 0
    startidx += lenght(":page")
    endidx = searchindex(txt, '\n', startidx)
    final_page_line = strip(txt[startidx:endidx])
else
    # do it manual
end
```

one could do that to extract multiple metas also to avoid rescanning the whole text.

**Comment by MichaelHatherly** [comment]
I'd really like something a bit more versatile that having everything at the end:

```jl
"""
!!author(Michael Hatherly)
!!license(MIT)

some text ...

!!args(
x: something about `x`.
y: something about `y`.
)

!!page(Lexicon.md/Exported/methods/1)
""" 
foobar(x, y) = x + y
```

Then allow the user to define metadata extraction methods with something like:

```jl
function Lexicon.extractmeta(::Meta{:author}, text, obj, mod)
    # do some custom parsing, add stuff to metadata and return some replacement text.
end
```

The `!!` syntax of course can be up for discussion.

**Comment by peter1000** [comment]
I think !!() is just fine

* extract this in Docile or in Lexicon.

* Do you want to allow within the brackets other brackets if not we still could do a simple index search and extract any !!()

**Comment by MichaelHatherly** [comment]
See #105 for continued discussion of metadata fields.

**Comment by peter1000** [comment]
maybe better to keep this as `:section` meta

**Comment by peter1000** [comment]
This seems to be `obsolete` by now with your idea from [here](https://github.com/MichaelHatherly/Lexicon.jl/issues/109#issuecomment-102042683)

```julia
out =
    document(
        config(...),
        section(
            # The manual section of the documentation.
            config(...),
            page(...),
            page(...),
            section(...))
        section(
            # The function reference section.
            page(...),
            other_pages...))

save(pdf("out.pdf", out))
save(markdown("out", out))
```
