### ISSUE TITLE
Start has no method error

### ISSUE THREAD

**Issue by multidis** [MichaelHatherly/Lexicon.jl#104]
Please see this issue, later comments mentioning Lexicon error:
https://github.com/robertfeldt/BlackBoxOptim.jl/issues/7

Any hope to sort out what is happening from the Lexicon side?

**Comment by MichaelHatherly** [comment]
Thanks, response in https://github.com/robertfeldt/BlackBoxOptim.jl/issues/7#issuecomment-98963828.
