### ISSUE TITLE
Extensible Metadata Syntax

### ISSUE THREAD

**Issue by MichaelHatherly** [MichaelHatherly/Lexicon.jl#105]
Allow user defined metadata fields to be embedded in docstrings.

Proposed syntax:

```jl
"""
!!author(Michael Hatherly)
!!license(MIT)

some text ...

!!args(
    x: ...
    y: ...
)

!!page(...)
!!section(...)
"""
```

where `!!` is used as a placeholder for the final syntax.

A user then defines

```jl
Lexicon.extractmeta(::Meta{name}, text::AbstractString, mod::Module, obj) = ...
```

where `isa(name, Symbol)`, ie. `:author`, `:license`, `:args`, `:page`, `:section`, etc.

`extractmeta` returns replacement text for the raw docstring. `text` is the raw text inside the brackets `(...)`.

**Comment by peter1000** [comment]
Sorry I'm not sure I understand that well (my English ;)
> text is the raw text inside the brackets (...).

This I understand

> where !! is used as a placeholder for the final syntax.
> extractmeta returns replacement text for the raw docstring. 

This is a bit confusing for my English

**placeholder** for the final syntax
**returns replacement text**

Do you want to replace the !! with the extracted txt? with `the raw text inside the brackets (...)`
> text is the raw text inside the brackets (...).

Sorry for that!

**Comment by MichaelHatherly** [comment]
> where !! is used as a placeholder for the final syntax.

I'm not decided on a final syntax for this feature so the `!!` is just for illustrative purposes currently.

`!!author(Michael Hatherly)` could return the text `"Author: Michael Hatherly"` and store the metadata `:author => "Michael Hatherly"`. So

```jl
"""
!!author(Michael Hatherly)
"""
```

would become
```jl
"""
Author: Michael Hatherly
"""
foo
```
and `metadata[foo][:author] = "Michael Hatherly"`.

The order of docstring processing would be:

* Pass the raw docstring to `extractmeta(::String, ::Module, obj)` which then parses the string at every `!!NAME(...)` and passes the `"..."` to `extractmeta(::Meta{:NAME}, "...", ::Module, obj)` for each  `!!` found.

* The resulting list of rawtext not parsed by `extractmeta` and text returned by `extractmeta(::Meta, ::String, ::Module, obj)` are then joined together and passed to `parsedocs` where it's converted into markdown AST or whatever `parsedocs` is defined to do.

(I'm just thinking this up as I go along, so the feedback is great, thanks.)

**Comment by peter1000** [comment]
Thanks. I understand that a bit more. 
`!!` purpose is clear now.

`metadata[foo][:author] = "Michael Hatherly".` is also clear

---

What was a bit confusing that you also want to alter the raw txt passed to parsedocs.

So it's a meta and becomes a template placeholder.

'!!author(Michael Hatherly)'

=> `Author: Michael Hatherly`

* How is that defined: **Author:** always the  meta Tag `author` becomse first upper letter and ends with colon space?

I will finish a small julia PR I accepted and than give that a try?

**Comment by MichaelHatherly** [comment]
> How is that defined

Something like, in pseudo code:

```jl
function extractmeta(rawtext, obj, mod)
    inbuf  = IOBuffer(rawtext)    
    outbuf = IOBuffer()
    while !eof(inbuf)
        if is!!(inbuf)
            name, text = parse!!(inbuf)
            write(outbuf, extractmeta(Meta{name}(), text, obj, mod)
        else
            write(outbuf, read(inbuf, Char))
        end
    end
    parsedocs(outbuf, obj, mod)
end

# ...

function Lexicon.extractmeta(::Meta{:author}, text, obj, mod)
    text = strip(text) # remove surrounding whitespace
    Docile.Cache.getmeta(mod, obj)[:author] = text # add to the object's metadata
    "Author: $(text)" # rewrite the displayed output
end
```

(Just a sketch, will need additional work of course.)

**Comment by peter1000** [comment]
If you really want to support unicode one would need to allow the user with what the `author` is replaced with. E.g. in simple chinese (I use always for unicode) they might prefer to have it: `笔者:` instead of `Author`

For customary meta this is fine they could define it  `!!笔者(...)` but what about default one like: `Page`.

Because you want to join this in the final parsed text I think you should allow also such be replaced by an appropriete word.

```
function Lexicon.extractmeta(::Meta{:author}, meta_replace::AbstractString, text, obj, mod)
end
```

Just a thought - I think it would be best to have a config for such - or only replace true `custom meta` and all others remove from the final parsed text.

**Comment by MichaelHatherly** [comment]
`extractmeta` could be overwritten by for `Meta{name}` so you could have `笔者: ...` instead of `Author: ...`. It should be possible to overwrite any `extractmeta` method like this.

`!!page(...)` would probably just return `""`, an empty string, so that it isn't shown in the body text of a parsed docstring. It would still show up in the automatically generated metadata at the end of the docstring as is done now.

**Comment by peter1000** [comment]
I'm not sure if I understood all correctly.

Anyway here would be a code which does what I understood with some little changes for config metatext replacement.

  
**SETUP**
[Config line](https://github.com/peter1000/Lexicon.jl/blob/master/src/config.jl#L35-L39)

```julia
Config(metadata_order = [(:author    , "笔者 : "),
                         (:license   , "License: "),
                         (:args      , "Arguments: "),
                         (:page      , "Output Section: ")]


# Used docstring

"""
!!author(Michael Hatherly)
!!license(MIT)

some text ...

!!args(
    x: ...
    y: ...
)

!!page(ConvertFunctions.md/Unicode/Asia/6)
!!section(Section should probably be gone)
"""
function example1()
end

```

**OUTPUT**


```julia
getmeta(mod, obj) 

Dict{Symbol,Any}(:license=>"MIT",:section=>"Section should probably be gone",:category=>:method,:args=>"\n    x: ...\n    y: ...\n",:author=>"Michael Hatherly",:code=>:(function example1()
    end),:page=>"ConvertFunctions.md/Unicode/Asia/6",:textsource=>(30,"/home/workerm/.julia/v0.4/testing/src/testing.jl"),:codesource=>(44,"/home/workerm/.julia/v0.4/testing/src/testing.jl"))


rawtext adjusted:

"""
笔者 : Michael Hatherly
License: MIT

some text ...

Arguments: 
    x: ...
    y: ...


Output Section: ConvertFunctions.md/Unicode/Asia/6
Section: Section should probably be gone
"""

```

[demo code](https://github.com/peter1000/Lexicon.jl/blob/master/src/render/md.jl#L12-L76)

I put some question in the code as comments

If a metadata is not in the `Config` mapped it falls back to the default: "$(ucfirst(string(meta_name))): $(text)"

**Comment by peter1000** [comment]
The advantage of replacing the final raw text seems that one can define the exact place within the output where a meta will appear  :+1:   instead off adding it all somewhere under `Details`. 

I will try to make a proper PR for the current Lexicon - with styling option.

**Comment by peter1000** [comment]
Ideas:

* Do not strip white space within the `!!meta(  Wanted extra space)` this will allow that emphasis style tags like `**meta:** Wanted extra space` works
* Allow in config a style to be associated with each: meta. will post later the details
* Replace the recently added : `metadata_order`

 ```
`metadata_order`      (default: `[:source]`) 
Metadata to include in the output in the defined order.
```
With a Dictionary `metadata`: Order is defined by the place in the docstring.
Dict(:metaname => (ReplacementText, StyleForReplacementText))

  * to skip a meta to be in the final output set "StyleForReplacementText" to empty like the `:page` below -- consideration: properly any empty lines should be removed 

```
config = Config(metadata = Dict(:author  => ("Author:", "**"),
                                :license => ("License:", "*"),
                                :fields  => ("Fields:", "####"),
                                :page    => ("Output Section:", ""),
                                )
              )
```

EXAMPLE docstring

```
"""
!!author( Michael Hatherly)
!!license( [MIT](https://github.com/MichaelHatherly/Lexicon.jl/blob/master/LICENSE.md))

Holds the parsed user query.

!!fields(

* `objects`: The objects that will be searched for in metadata.
* `modules`: Modules to be searched through for documentation.
* `index`:   1-based, for picking an individual entry to display out of a list.)

!!page(Lexicon.md/Exported/1)
"""
type Query
    objects :: Vector
    modules :: Set{Module}
    index   :: Int

    Query(objects, modname, index) = new(objects, Set([modname]), index)
    Query(objects, index)          = new(objects, documented(), index)
end

```

SHOULD output something like.

```
"""
**Author:** Michael Hatherly)
*License:* [MIT](https://github.com/MichaelHatherly/Lexicon.jl/blob/master/LICENSE.md)

Holds the parsed user query.

#### Fields:

* `objects`: The objects that will be searched for in metadata.
* `mods`:    Modules to be searched through for documentation.
* `index`:   1-based, for picking an individual entry to display out of a list.

"""
```

---

Lexicon.**Query**

**Author:** Michael Hatherly)
*License:* [MIT](https://github.com/MichaelHatherly/Lexicon.jl/blob/master/LICENSE.md)

Holds the parsed user query.

#### Fields:

* `objects`: The objects that will be searched for in metadata.
* `mods`:    Modules to be searched through for documentation.
* `index`:   1-based, for picking an individual entry to display out of a list.

---

**Comment by peter1000** [comment]
The beauty of this above instead of putting all straight in the `markdown` is:

* Easily replace: metatags text for all objs within the config. (though in praxis I'm not sure how much it is used)

* Easily replace metatags style: this one I think is quite useful for instance one changes a MkDocs theme a other style might fit better.

* Easily disable metatags from output: just specify the meta with an empty style (empty style is just a thought but the idea is here) Also quite useful. 

  EXAMPLE: one could have a much more detailed explanation something like this

```
.....

.....

!!complexdetails(

bla bla bla......


bla bla bla......
)

```

And produce very easily two versions of documentation: a Simple introduction documentation and an detailed one for download or whatever.

Run for simple docs:

```
config = Config(metadata = Dict(:complexdetails  => ("Details:", ""),))
```

Run for extendet docs:

```
config = Config(metadata = Dict(:complexdetails  => ("Details:", "###"),))
```

I think this is very feasable and in the end not even so much work to implement.

**Comment by peter1000** [comment]
Other usage idea:

Add to the comments any TODO and when generating the docs just skip them easily

```
config = Config(metadata = Dict(:todo  => ("TODO:", ""),))

"""
Returns the extracted meta

!!todo(Needs still some cleaning up of the extraction of the meta.
This text should not be in the final documentation.)
"""
function extractmeta()
end
)
```

**Comment by MichaelHatherly** [comment]
Oops, apologies @peter1000. I've been working on this this morning https://github.com/MichaelHatherly/Docile.jl/commit/fe48d2a1816aa6da4d94dbcf503ba002754275da. Since I didn't have internet access until just now, I've only just seen this :( sorry.

I'll read through your ideas now.

**Comment by peter1000** [comment]
No problem at all ;) I will look also through your implementation which I suppose it more sophisticated .. and see if I can find something to comment on.

**Comment by MichaelHatherly** [comment]
> instead off adding it all somewhere under `Details`

Yes, that's part of the idea. We can define `metamacro` methods that return text to replace the original.

> Do not strip white space

That's completely configurable by the package author.

> Allow in config a style to be associated with each

`Config` is only used for `save`ing external docs though, so doesn't have an effect on REPL / interactive docs at all, and should probably remain that way.

> EXAMPLE docstring

For that example something like this can be used:

```jl
import DocileExperimental.Formats, DocileExperimental.Cache

function Formats.metamacro(::Formats.MetaMacro{:author}, body, mod, obj)
    Cache.getmeta(mod, obj)[:author] = strip(body)
    string("**Author:**" body)
end

function Formats.metamacro(::Formats.MetaMacro{:license}, body, mod, obj)
    Cache.getmeta(mod, obj)[:license] = body
    string("**License:**" body)
end

function Formats.metamacro(::Formats.MetaMacro{:fields}, body, mod, obj)
    # do some parsing to extract fields

    """
    #### Fields    
    
    $(body)
    """
end

function Formats.metamacro(::Formats.MetaMacro{:page}, body, mod, obj)
    Cache.getmeta(mod, obj)[:page] = strip(body)
    return ""
end
```

This extends to anything you can think up hopefully. Check the Extensions folder in the Docile repo for a `!!format(MySpecialFormat)` for deciding on the format of an individual docstring.

**Comment by MichaelHatherly** [comment]
> I can find something to comment on.

Comments would be much appreciated.

**Comment by peter1000** [comment]
> Config is only used for saveing external docs though, so doesn't have an effect on REPL / interactive docs at all, and should probably remain that way.

I thought so do 

> the above example you gave.

```
function Formats.metamacro(::Formats.MetaMacro{:author}, body, mod, obj)
    Cache.getmeta(mod, obj)[:author] = strip(body)
    string("**Author:**" body)
end

function Formats.metamacro(::Formats.MetaMacro{:license}, body, mod, obj)
    Cache.getmeta(mod, obj)[:license] = body
    string("**License:**" body)
end
```

Maybe I misunderstand it but personally I think it is not very userfriendly.

Often people do not want invest too much time in documentation (especially with julia coders ;).

If one has to add for each `!metaplaceholder` a function like that I think it is not flexible enough.  Just talking from the point of generating final docs not interactive.

I think at least there should be the flexibility as suggested with the config [start comment]](https://github.com/MichaelHatherly/Lexicon.jl/issues/105#issuecomment-99807382)

Probably one can use your code and implement on top of it the functionality.

**Comment by MichaelHatherly** [comment]
> I think it is not very userfriendly.

The `metamacro` is for package authors, not users. True, it's a step up in complexity compared to a `Dict` for simple customisation, but for anything complex you really want to have the full power of julia to do things.

> Often people do not want invest too much time in documentation

 We can add as many as we find useful the the package. 

> If one has to add for each !metaplaceholder a function like that I think it is not flexible enough. Just talking from the point of generating final docs not interactive.

The definition `Formats.metamacro{name}(::Formats.MetaMacro{name}, ...)` covers all possible names, so if you want the default behaviour of just saving the `body` into metadata field `name` and splicing it back in then that has you covered.

**Comment by peter1000** [comment]
I think I will just give it a run and see how this works - also see if I run into any issues.

**Comment by MichaelHatherly** [comment]
Interestingly you can also define "variables" like so:

```jl
function Formats.metamacro(::Formats.MetaMacro{:author}, body, mod, obj)
    if isempty(body)
        return Cache.getmeta(mod, obj)[:author]
    else
        Cache.getmeta(mod, obj)[:author] = strip(body)
        return ""
    end
end
```

If you wanted to do something like

```jl
"""
!!author(Michael Hatherly)

The authors name is !!author().
"""
```

give you

```


The authors name is Michael Hatherly.
```

Pretty cool I think :)

**Comment by MichaelHatherly** [comment]
> I think I will just give it a run and see how this works - also see if I run into any issues.

It can all still do with some streamlining, so this won't be the final interface I'm sure. Definitely not set in stone.

**Comment by peter1000** [comment]
Just a quick question: how would one use that for an simple test

```
require("DocileExperimental.jl")

# Get the raw docstrings from the `Cache` module.
DocileExperimental.Cache.getraw(DocileExperimental.Cache)

# Get the parsed docstrings from the `Collector` module.
# Since `PlaintextFormatter` is a simple passthrough the output is the same as above.
DocileExperimental.Cache.getparsed(DocileExperimental.Collector)

# Get all metadata dictionaries for objects documented in module `Formats`.
DocileExperimental.Cache.getmeta(DocileExperimental.Formats)
```

**Comment by MichaelHatherly** [comment]
> how would one use that for an simple test

To test out new `metamacro` definitions? Define a module like

```jl
module Sandbox

require("/home/mike/.julia/v0.4/Docile/src/Experimental/DocileExperimental.jl")

import DocileExperimental: Formats, Cache

function Formats.metamacro(::Formats.MetaMacro{:author}, body, mod, obj)
    if isempty(body)
        return Cache.getmeta(mod, obj)[:author]
    else
        Cache.getmeta(mod, obj)[:author] = strip(body)
        return ""
    end
end

"""
!!author(Michael Hatherly)

!!author(), !!author().
"""
Sandbox

end
```

and then at the REPL do:

```
julia> require("Test/Sandbox.jl")

julia> DocileExperimental.Cache.getparsed(Sandbox, Sandbox)
INFO: Updating cached package list...
INFO: Initialising cache for 'Sandbox' and related modules...
 Sandbox ✓
INFO: Succcessfully initialised package cache.
"\n\nMichael Hatherly, Michael Hatherly.\n"

julia> DocileExperimental.Cache.clear!()
```

**Comment by peter1000** [comment]
Thanks

**Comment by MichaelHatherly** [comment]
Largely completed in DocileExperimental. Further discussions regarding this should be opened in the Docile repo.
