### ISSUE TITLE
Add page order option.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#106]
IDEA:

MkDocs uses something like this:

```
pages:
    - ['index.md', 'Introduction']
    - ['manual.md', 'Manual', 'Overview']
    - ['api/Lexicon.md', 'API', 'Lexicon']
    - ['api/index.md', 'API', 'Index']
```
We could have something similar with a couple of advantages.

* Plan is in the end to be able to auto- generate 3rd party MkDocs `mkdocs.yml` which would than be more in line with the rest of the documentation.
e.g. the Index would be in the same order as the MkDocs pages.

**Comment by MichaelHatherly** [comment]
Sounds good. Reducing what needs to be kept up to date would be nice.

**Comment by peter1000** [comment]
I think this could be closed with the new `document(...)`
