### ISSUE TITLE
Unclear Issue: Waiting to be decided when a better real example exists

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#107]
this comes from Docile [comment]( https://github.com/MichaelHatherly/Docile.jl/issues/89#issuecomment-100291404)

It is yet unclear if this does not already work or not. Waiting to be decided when a better real example can be worked through.

Case Idea/Question:

Sometimes one uses a longer docstring: like the Lexicon `save` uses.

Currently we have the `file"docs/save.md"` which is changed in the DoxileExperiment to: I think I undersood it like this `"docs/save.md"`.

**Question:**
I never liked the one for [Config](http://lexiconjl.readthedocs.org/en/latest/api/Lexicon/#type__config.1) too much because it created a very long entry which in my opinion  disrupts a bit the flow. It was even worth when we had all below the `save` method.

Anyway: In the future with a more flexible Section System I think such an long entry might deserve a separate output file without necessarily become a separate module. (assume we have all below the `save` function.

Options:

#### Manual page

Write a manual page for `save.md` and at the function a link to it. Because we still want to have the function an docstring so it shows up with the rest of it and also in the index.

Something like:

* Save the small  docstring with all other methods in: **Lexicon.md** > Exported > Methods > 1. item below the header

* Save the long  docstring in an other file: **Details.md** > Exported > Methods >  5. item below the header

```julia
"""
Saves the module documentation to file.

[Extended documentation](Details.md/exported_methods_save.md)   # or whatever the final link is

!!section(Lexicon.md/Exported/Methods/1)      # only the small info to Exported/Methods

# in save.md define a !!section(Details.md/Exported/Methods/5)
"""
function save()end

```

? Does the DocileExperimental extract our `!!metadata() also from such manual pages?

#### Find other solution

Don't have an anwser yet that's why I ask what you think?

**Comment by MichaelHatherly** [comment]
Is this kind of thing covered by ``!!longform(...)``? Or am I misunderstanding what you'd like here?

**Comment by peter1000** [comment]
I don't think so - but not sure: if you do not mind I would like to keep that still open till we have written some docs with the `section` meta.

**Comment by MichaelHatherly** [comment]
Sure, no prob.

**Comment by MichaelHatherly** [comment]
Closing now. We can reopen with a proper title if/when necessary.
