### ISSUE TITLE
Compose.jl-like API for creating static documentation.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#110]
**Compose.jl-like API for creating static documentation.**

If you don't mind I would like to give this a try as I'm interested in it (REPL integration and such is not so much of interest to myself): just saying so we might not overlap too much.

Will use your [outline](https://github.com/MichaelHatherly/Lexicon.jl/issues/109#issuecomment-102042683) as a basic reference point. I have already some ideas.

**Comment by MichaelHatherly** [comment]
You're welcome to have a go at implementing this. I was planning to add it along with a *large* change to the package structure, though that won't be happening for a little while. We can coordinate efforts later on though.

**Comment by peter1000** [comment]
I hope you don't mind me coming back to your example.
I just want to make sure I understand your thoughts correctly so this is a bit longer.

> [comment](https://github.com/MichaelHatherly/Lexicon.jl/pull/111#issuecomment-102617370)
> We should be able to add multiple configs to a single node (document, section, or page) with later configs overriding earlier ones.
> Also arbitrary keyword arguments for nodes that override all config objects for a node would be good as well

Slightly adjusted example of yours:

```julia
page_base_config = Dict(:a => 0, :b => 5, :c => 18)

page(
    "reference.md",
    config(a = 1, b = 2),
    Docile,
    "Some intermediate text.",
    config(c = 0,),
    Docile.Cache,
    b = 3,
    Docile.Formats,
    config(a = 20, c = 0,),
    Docile.Collector
)
```

I will show how I understand this: and how the applied *config* changes: I guess from your past comments that you meant `config(...)` uses a deepcopy of *page_base_config*.

**"reference.md"**: process 'contents of reference.md' with *page_base_config* applied? `Dict(:a => 0, :b => 5, :c => 18)` Not 100% what you had in mind?

**config(a = 1, b = 2)**: modify a deepcopy of *page_base_config* result:  `Dict(:a => 1, :b => 2, :c => 18)`

**Docile**: I'm not 100% sure but I guess process all docstrings from module: *Docile*

* *Docile* will be processed / rendered with a final config:  `Dict(:a => 1, :b => 2, :c => 18)`

**"Some intermediate text."**: This is just a Text processed / rendered with a config:  `Dict(:a => 1, :b => 2, :c => 18)`

**config(c = 0,)**: modify a deepcopy of *page_base_config* result: `Dict(:a => 0, :b => 5, :c => 0)`

**Docile.Cache**: process module: *Docile.Cache* with config: `Dict(:a => 0, :b => 5, :c => 0)`

**b = 3**: Overwrite the actual *page_base_config* result: `page_base_config = Dict(:a => 0, :b => 3, :c => 18)`

* if that is the case: would you mind if we have here somthing like `updateconfig!(b, 3)`.

**Docile.Formats**: the module will be processed / rendered with a final config:  `Dict(:a => 0, :b => 3, :c => 18)`

**config(a = 20, c = 0,)**: modify a deepcopy of the *page_base_config* (which was overwritten above) result: `Dict(:a => 20, :b => 3, :c => 0)`

**Docile.Collector**: the module will be processed / rendered with a final config: `Dict(:a => 20, :b => 3, :c => 0)`

---

RELATED QUESTION:

in your original [comment](https://github.com/MichaelHatherly/Lexicon.jl/issues/109#issuecomment-102042683) you had at the end:

```
save(pdf("out.pdf", out))
save(markdown("out", out))
```

I'm correct to assume that the methods: `pdf` or `markdown` do the actual processing of the above document structure?

I'm a bit confused with your example: resulting internally in 
> [comment](https://github.com/MichaelHatherly/Lexicon.jl/pull/111#issuecomment-102617370)

```julia
page([
        "<contents of reference.md>",
        Docile,
        "Some intermediate text.",
        Docile.Cache,
        Docile.Formats,
    ],
    config(
        a = 2,
        b = 3,
    ),
)

```


**Thanks a lot** - I know it is longer - hope I understood it the same as you had it in mind ;) but I'm not so sure.
