### ISSUE TITLE
Predefine supported generic `config` keys

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#123]
Already defined by current code.

- ``:id``
- ``:filter``
- ``:sorter``
- ``:rootdir``

Others

- ``:builddir``
- ``:markdown``

**Comment by MichaelHatherly** [comment]
``rootdir`` and ``builddir``. Or perhaps dropping the ``dir`` part.

**Comment by peter1000** [comment]
What are they both suppose to define? 

`rootdir`
`builddir` - the output directory or something like that?

**Comment by peter1000** [comment]
We need definitely decide on what we do for output names.

For markdown I had implemented in my last commits an `:outname` for each node:

- `Section :outname`:  would produce a subfolder: with an additional option to skip that e.g. for index files with mkdocs.

- `Page :outname`: would result in an actual file name.

I think probaby `html` might use a similar output structure but `pdf` not.

---

What do you think: should we use the `:id` instead?

**Comment by peter1000** [comment]
`:id`  seems to be also defined but not set like the rest of configurations `id = :myid`

**Comment by MichaelHatherly** [comment]
> What do you think: should we use the ``:id`` instead?

``Lexicon.Render.get_full_id(::Node)`` implements this concept. Returns a ``Vector{Symbol}`` with the auto generated full path of node ids. Automatically generated names are just based on the node type and position in the ``children`` vector, which I feel is clearer than using text from the children.

For markdown output that folder/file structure sounds fine to me. HTML would be similar.

> ``:id`` seems to be also defined but not set like the rest of configurations ``id = :myid``

That's still being set by any ``Symbol`` in the argument list to each node constructor. I fine the syntax quite nice:

```jl
document(:custom,
    section(:manual,
        ...
    ),
    section(:reference,
        ...
    ),
)
```

A keyword ``id = ...`` will override a symbol in the argument list.

**Comment by MichaelHatherly** [comment]
Related to node ids: I'm thinking that cross-referencing can just be done using

```julia
"""
This is a random docstring. This [link](docs/manual/introduction#anchor).
"""
```

```jl
document(:docs,
    section(:manual,
        page(:introduction,
            "page.md",
        )
    )
)
```

which would link to some anchor in "page.md". Seems like that will match up with your proposed folder structure for markdown/html I think?

**Comment by peter1000** [comment]
What are they both suppose to define? 

`rootdir`
`builddir` - the output directory or something like that?

**Comment by peter1000** [comment]
> Related to node ids: I'm thinking that cross-referencing can just be done using

Yes similar to what I had in mind. the question is an unique anchor which stays always the same even if other filters are applied or the source code is changed and a couple of functions or types are added or removed?

Otherwise it would be quite nice.

**Comment by MichaelHatherly** [comment]
``rootdir`` folder to use for resolving external files. Used [here](https://github.com/MichaelHatherly/Lexicon.jl/blob/0c8ef18aa503fa780452b9367110cb6aa97c73dd/src/Render/utilities.jl#L10-L16).

``builddir`` would be where all ``save`` calls send their output so as not to clutter up the working directory. ``save`` for different formats could create subdirectories such as ``markdown``, ``latex``, ``html`` etc.

> the question is an unique anchor which stays always the same even if other filters are applied or the source code is changed and a couple of functions or types are added or removed?

If the target remains on the same ``page`` then it should be fine.

**Comment by peter1000** [comment]
> builddir would be where all save calls send their output so as not to clutter up the working directory. save for different formats could create subdirectories such as markdown, latex, html etc.

I had previously used `:outdir` but I think I would leave the dir instead of only `root` - `build`

**Comment by peter1000** [comment]
**just a question**: what about adding one format specific one?

`:pdf`, `:markdown`, `html`, `latex`

**Comment by MichaelHatherly** [comment]
Yes, keeping the "dir" will probably lead to less confusion.

> just a question: what about adding one format specific one?

For ``compile!`` to make use of?

**Comment by peter1000** [comment]
To have the option to supply a format specific configuration per node.

For instance there should be an option for `markdown` to disable that the `index.md` is generated in a subfolder when using `mkdocs`

I had it [here](https://github.com/MichaelHatherly/Lexicon.jl/pull/116/files#diff-01285fe4a25bbc4da684aa18148e934eR18) `:nosubdir` config for such Section.

`pdf` definately does not need such config option.

**Comment by MichaelHatherly** [comment]
> For instance there should be an option for markdown to disable that the index.md is generated in a subfolder when using mkdocs

Is that needed prior to actually outputting the markdown files?

**Comment by MichaelHatherly** [comment]
If it is then that's fine.

**Comment by peter1000** [comment]
I think it should be per node defineable: and I'm not so sure the configuration passed to  save format Markdown(<<config>>) will allow such - at least not easily.

```julia
save(out, Markdown(<<config>>))
save(out, LaTeX(<<config>>))
```

having one format specifig config option alows that to be a Dictionary in case one needs / wants to store more. (Who knows which formats people might like to add outside of Lexicon?)

**Comment by peter1000** [comment]
Theoretically such format specific config could replace the one which you wanted to pass to save above? - than all settings are in one place - the document.

```julia
out = document(
    :one,

    markdown = {.......},
    )
```

but passing an extra config for format specific general render settings seems also fine.

**Comment by MichaelHatherly** [comment]
I figured that separating output config data that's specific to only one format would have the benefit of not needing to change internals of ``compile!`` when we add additional formats. Counter examples to that are fine -- If we're not able to easily achieve the same effect by pasing configs to ``save`` then I'm not against adding keyword args to the nodes.

**Comment by peter1000** [comment]
In the new Docile (julia 0.4/0.5) not anymore relevant.
