### ISSUE TITLE
save doesn't output everything

### ISSUE THREAD

**Issue by lendle** [MichaelHatherly/Lexicon.jl#134]
I see that you're working on the `rewrite` branch of Docile, and it looks like functionality there will supersede `save`, but I figured I'd file this anyway in case anyone else has an issue.

`save` doesn't output everything. It seems to depend on the content of the doc string. From what I can tell, if a docstring has more than 4 or 5 lines, it's not saved. It shows up in the help in the repl though.

Minimal example:

Create a package called `TestDocs`:
```{julia}

module TestDocs

export f, g

"
Prints stuff
"
f(a) = println(a)

"
a
b
c
d
e
"
g(x) = x

end
```

Then,  run 

```julia
using Lexicon, TestDocs

fname = tempname() * ".md"
save(fname, TestDocs)

println(open(readall, fname))

```

The docs for `g` are missing:
```
# TestDocs

## Exported

---

<a id="method__f.1" class="lexicon_definition"></a>
#### f(a) [¶](#method__f.1)

Prints stuff


*source:*
[TestDocs/src/TestDocs.jl:8](https://github.com/lendle/TestDocs.jl/tree/e394074082681173c81ea9d5789ebda3f6f84965/src/TestDocs.jl#L8)
```

This works:
```julia
help?> g
search: g gc get gcd get! gcdx gperm gamma global golden givens getpid getkey gensym GenSym getfield gradient getindex GotoNode graphemes getipaddr gc_enable gc_disable GlobalRef gethostname getaddrinfo get_rounding get_zero_subnormals

  a b c d e
```

**Comment by MichaelHatherly** [comment]
Number of lines doesn't appear to be the only factor causing docs to be missed. If you remove all the text from `g`'s docstring it does pick up `g`...

```julia
module TestDocs

export f, g

"
Prints stuff
"
f(a) = println(a)

"





"
g(x) = x

end
```

Emptying all you docs probably isn't the best fix though :)

Can you try out the following diff applied to Docile? Seems to fix your test case for me.

```diff
diff --git a/src/Runner/lookup.jl b/src/Runner/lookup.jl
index 54e47df..e4e91be 100644
--- a/src/Runner/lookup.jl
+++ b/src/Runner/lookup.jl
@@ -19,7 +19,7 @@ function findmethods(state::State, ex::Expr, codesource)
         # Filter out methods defined in different files.
         file′ == file || continue
         # Calculate the line distance and update ``mset`` accordingly.
-        Δ′ = line′ - line
+        Δ′ = abs(line′ - line)
         if 0 ≤ Δ′ < Δ
             Δ = Δ′
             empty!(mset); push!(mset, m)
```

**Comment by lendle** [comment]
That seems to have fixed it. I never would have found that on my own, thanks!

**Comment by MichaelHatherly** [comment]
Tagged version with this fix in https://github.com/JuliaLang/METADATA.jl/pull/4223.
