### ISSUE TITLE
Duplicate entries generated for methods with default arguments.

### ISSUE THREAD

**Issue by MichaelHatherly** [MichaelHatherly/Lexicon.jl#17]

**Comment by MichaelHatherly** [comment]
Quoting from other issue linked:

> It's mostly just an issue of not showing duplicate Entry objects in the generated output (like the repl output already does). Aggregating all objects that share a common Entry and displaying the aggregation would probably look better.

**Comment by peter1000** [comment]
just saw this commit: not sure if it is at all related to something of Lexicon/Docile but thought you might want to know about it

[don't emit two copies of a definition in `@doc`](https://github.com/JuliaLang/julia/commit/556bbe3eb16d23338092bf8d5ca3a760e1c8c99f)

**Comment by MichaelHatherly** [comment]
Docile is not using the ``FuncDoc`` object. Internally it's quite different. I'll have a look at some point though.

(This really has nothing to do with this issue though.)

**Comment by peter1000** [comment]
should be closed in favour of a combined signature [issue](https://github.com/MichaelHatherly/Lexicon.jl/issues/118)
