### ISSUE TITLE
Show docs summary by default, not the full docs.

### ISSUE THREAD

**Issue by MichaelHatherly** [MichaelHatherly/Lexicon.jl#18]
Perhaps just the first paragraph or signature unless an "extended" flag to a quiery:

```
help?> foobar
help?> foobar +
```

or something other than ``+``.

Ref: https://groups.google.com/forum/#!topic/julia-users/wBZGlzFo7eI

**Comment by tshort** [comment]
At the REPL, I'd prefer the full help. Summaries are nice for package overviews.

**Comment by MichaelHatherly** [comment]
At the moment I'll be keeping the full help output in the REPL since I haven't found a good solution to this yet. Thanks for the input.

**Comment by tshort** [comment]
I'd like to amend my preference. If a earch query comes back with one entry (or other small number), I'd like to see everything. If it finds many, I'd rather see truncated versions (something like the first 5 lines or 2 paragraphs).

**Comment by MichaelHatherly** [comment]
The output can definitely be a little verbose at times! Assuming the size of a terminal window can be found out in Julia, then deciding whether to display summaries or full docs shouldn't be too difficult to achieve.

Further, if each summary is prefixed with an index `1..N` then `?` could take an optional `Int` as a second parameter that only shows the `ith` entry. Looking up docs could then be as follows:

* `? qeury-term-with-multiple-results`
* see a numbered list of results. Only the first line of each, or maybe just the signature even.
* press up arrow to display `? qeury-term-with-multiple-results` and append `5`.
* Output only shows the 5th entry from the previously listed output.

**Comment by tshort** [comment]
Great ideas for multiple entries!

**Comment by MichaelHatherly** [comment]
Implemented in 0f60c19538b87887b23d728e33e3e776f66b85ac.
