### ISSUE TITLE
Show keyword arguments in generated output

### ISSUE THREAD

**Issue by mpastell** [MichaelHatherly/Lexicon.jl#19]
Great work on Lexicon. I'm just starting to use it. 

I think it would be nice if keyword arguments would also show up in the generated docs. I think this is currently not the case?

For example, instead of having 
`[method] —  save(file::String,modulename::Module)` 

in Lexicon docs you'd get something like:

`[method] —  save(file::String,modulename::Module; mathjax = false)`

**Comment by dpo** [comment]
I opened a related issue here: https://github.com/MichaelHatherly/Docile.jl/issues/49

**Comment by MichaelHatherly** [comment]
Yeah, seems more suitable to keep this one open.

**Comment by peter1000** [comment]
In the process of the new `Config` I will give a try as I want to include such.

**Comment by peter1000** [comment]
Just wondering if one documents something with a good number of arguments like numpys [savetxt](http://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html#numpy-savetxt) - how would such look in our case with all the long types in the first line.

**Comment by peter1000** [comment]
should be closed in favour of a combined signature [issue](https://github.com/MichaelHatherly/Lexicon.jl/issues/118)
