### ISSUE TITLE
Links to files point to local dir, not Github repo

### ISSUE THREAD

**Issue by dpo** [MichaelHatherly/Lexicon.jl#20]
I noticed that all links to specific lines in files point to my local dir, and not to the Github repository. I presume the [url function](https://github.com/MichaelHatherly/Lexicon.jl/blob/master/src/render.jl#L69) is responsible for this?! When I run the `Pkg.Git` commands from the Julia prompt, they seem to point to the Github repo, but I may be mistaken as to what they're expected to return. What could be the cause of this?

**Comment by MichaelHatherly** [comment]
Not too sure what could be causing that. Is the package registered as a github repository so I can check it out myself to see?

Also, are you referring to the urls in the html output or the console output?

**Comment by dpo** [comment]
Both types of URLs point to my local dir. In the console, perhaps that's for the best. But in the online documentation, it would be great if they could point to the Github repo.
- Github repo: https://github.com/dpo/MUMPS.jl
- Documentation: http://dpo.github.io/MUMPS.jl/MUMPS.html

**Comment by MichaelHatherly** [comment]
Hmm, that's quite odd. My own docs for Docile and Lexicon both point toward the right places. I'm not
hugely cued up on git though. Have you set up git as in the [manual](http://docs.julialang.org/en/latest/manual/packages/#initial-setup)?

It's the same ``url`` code that's used for method urls in IJulia. Where do the url's point to if you have a notebook open?

**Comment by dpo** [comment]
Sorry for the delay; it took me a bit of time to get IJulia going again. Yes, the URLs also point to local files in IJulia. I noticed another phenomenon. At https://github.com/dpo/linop.jl/blob/master/src/linop.jl#L312 there are two methods named `opDiagonal` (the other one is at line [320](https://github.com/dpo/linop.jl/blob/master/src/linop.jl#L320)). In the terminal, `query(opDiagonal)` only returns documentation on the second one. In IJulia, the same command returns documentation on both!

In LightTable, the command also returns the documentation on both methods, though the color codes aren't processed and it's quite difficult to read. I'll point to this thread on the Juno tracker.

**Comment by MichaelHatherly** [comment]
The color codes should only be showing up in the console. Lexicon is meant to output html in cases such as Juno/IJulia. Perhaps I've missed some recent changes in some of Lexicon's dependencies, since I'm sure this used to work fine.

**Comment by MichaelHatherly** [comment]
I'll look into trying to recreate the url problem.

**Comment by mpastell** [comment]
I had the same issue when I ran Lexicon using a version of `Weave.jl` symlinked to .julia/v0.3, but I was  able to fix it by removing the symlink and installing the package using `Pkg.clone` instead.

**Comment by MichaelHatherly** [comment]
@mpastell thanks! Might be [this](https://github.com/MichaelHatherly/Lexicon.jl/blob/dca333d32d86c83264054024514d3198ef3086b3/src/render.jl#L78) condition that was causing trouble there since the file and root probably won't match if I'm reading it correctly. Any chance that is would help for your case @dpo?

**Comment by dpo** [comment]
There's definitely a noticeable improvement here! Thanks for spotting that symlinks could be the culprit! Now links point to my Github repository, but unfortunately, they lead to a 404 because they point to a file `MUMPS.jl`, which is in fact named `mumps.jl`. Did `Lexicon` just use the module name instead of the file name?

**Comment by MichaelHatherly** [comment]
As far as I'm aware, the main file in a `src/` folder of a Julia package should be named the same as the module itself. I don't think that this is a "set in stone" kind of rule, just what `Pkg.generate` should produce. Are you using a case-insensitive OS?

**Comment by dpo** [comment]
I was checking the Julia docs about that, but I didn't see anything (might have missed it). I created the package manually, not with `Pkg.generate()`.

**Comment by MichaelHatherly** [comment]
Uppercasing the file name might be all that's needed. `using` should still be able to locate it I'd think.

**Comment by dpo** [comment]
Sorry for leaving this open all this time. The problem is resolved if I build the doc from within `~/.julia` and the package and module file have the same name. Many thanks for the help!

**Comment by MichaelHatherly** [comment]
No worries. Even though it had a milestone assigned I managed to loose track of it also.
