### ISSUE TITLE
If julia > 0.3 don't require Markdown

### ISSUE THREAD

**Issue by hayd** [MichaelHatherly/Lexicon.jl#28]
At the moment you are using the imported Markdown rather than the version in Base (which potentially is a different version, e.g. supporting fewer MD types - tables, but at best is the same code). Can this be required only for julia < 0.4 ?

(It's not clear to me how you declare this http://julia.readthedocs.org/en/latest/manual/packages/#man-package-requirements)

Edit: Note you also get this warning, thought that is no big deal, but shows the code bases are different.
```
WARNING: deprecated syntax "[a=>b, ...]" at /Users/andy/.julia/v0.4/Markdown/src/render/terminal/formatting.jl:4.
Use "Dict(a=>b, ...)" instead.
```

**Comment by MichaelHatherly** [comment]
I think just a runtime check of `VERSION` would be the simplest way to do this and then either import `Markdown` or `Base.Markdown`. Is there a particular reason not to backport the markdown changes to the markdown package?

**Comment by hayd** [comment]
No, I can/will backport changes, but why install the package if it's in Base?

**Comment by hayd** [comment]
I think it'll lead to some weird bugs down the line, runtime check will be ok - will put together a PR.

I wonder if installing Markdown on 0.4 can be a no-op...

**Comment by MichaelHatherly** [comment]
Yeah, I'd rather avoid doing anything too complex if we can avoid it. Given that Markdown.jl doesn't have any binary deps, installing it in 0.4 doesn't seem like much of a problem.

Thanks for all the effort you've been putting into markdown features recently!

**Comment by hayd** [comment]
I tried to remove the import (on 0.4), I was surprised that there is a difference in Markdown:

    ERROR: LoadError: LoadError: UndefVarError: BlockCode not defined

is this not ported to base / should it be?

*(Another related thing is I think it would be useful to subtype Inline and Block, although since there's no multiple inheritance.... dang!)*

Thanks for all you work on docs! :)

**Comment by MichaelHatherly** [comment]
See this issue for details: https://github.com/one-more-minute/Markdown.jl/pull/5. The error's from `doctest` trying to find code blocks to test. It'll probably just need a compat fix until a new version is tagged of Markdown.jl.

**Comment by MichaelHatherly** [comment]
`Markdown` backported in 110979631021a0b2bba6cb101f1590d45f09bd1d.
