### ISSUE TITLE
Wrong methods error when parsing outer constructor function

### ISSUE THREAD

**Issue by multidis** [MichaelHatherly/Lexicon.jl#30]
Trying to generate documentation [here](https://github.com/multidis/FinancialSeries.jl/blob/master/src/financialtimeseries.jl#L25)

    save("docs/api.md", FinancialSeries)

ERROR: Wrong methods found: ``FinancialTimeSeries{Float64,Any,Union(AbstractCurrency,AbstractInstrument)}((Union(Array{DateTime,1},Array{Date,1}),Array{T<:Float64,N},Array{ASCIIString,1},Union(AbstractCurrency,AbstractInstrument)))``. **Please file a bug report.**

**Comment by MichaelHatherly** [comment]
Thanks for the report. Is this happening on julia 0.3 or 0.4 (or both)? Could you provide the output of `versioninfo()`.

**Comment by multidis** [comment]
This is with Julia 0.3

    versioninfo()

Julia Version 0.3.5
Commit a05f87b* (2015-01-08 22:33 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: AMD FX(tm)-8350 Eight-Core Processor
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Piledriver)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by MichaelHatherly** [comment]
Should be resolved by MichaelHatherly/Docile.jl@c0b6308ea84b38bb240cc907bd53346e9ed592f2 and new tagged version of Docile, 0.4.3. I've tested on your fork of `FinancialSeries.jl` and all docstrings are now being captured. If you are still running into this issue we can reopen this.

**Comment by multidis** [comment]
Yes the comment seems to be parsing correctly now, thanks @MichaelHatherly for the quick fix.
