### ISSUE TITLE
Question: markdown output: header size

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#39]
Just started with Lexicon/Docile and it seems that for api the documented item: e.g. function is output as `h4`
```
#### query(f::Function, sig::(Any..., ))
```

Is there a way to customize this.

**Comment by MichaelHatherly** [comment]
There isn't a very direct route at the moment unfortunately. Being able to customise output in a more useable way is definitely something I'd like get work though. I just haven't come up with a nice interface yet for it.

**Comment by peter1000** [comment]
I really like your documentation pkg and together with [mkdocs](http://www.mkdocs.org/) it helps to switch from `python Sphinx`.
So for now I will have a simple go at this (because I want to write at least some docs for any pkg from the start). Will send a PR if you need something more fancy you can always reject it ;)

**Comment by MichaelHatherly** [comment]
PRs are definitely welcome; ping me if have any queries.

**Comment by peter1000** [comment]
Solved merged PR #42

**Comment by peter1000** [comment]
@MichaelHatherly  Just a question which came up:

This does only effect the autogenerated API docs, doesn't? and not any manual added pages. If so we should mention this in the documentation?

**Comment by MichaelHatherly** [comment]
Only the autogenerated pages. The manual pages shouldn't even be passing through the system I think.

**Comment by MichaelHatherly** [comment]
Clarification in the documentation would be good to have.
