### ISSUE TITLE
Related: mkdocs readthedocs theme: renders code block italic with cons

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#40]
Because Lexicon uses the `mkdocs readthedocs theme` I thought you should know.
Filled a new Issue: https://github.com/mkdocs/mkdocs/issues/411

you can also close this if you want.

Cheers
P

**Comment by MichaelHatherly** [comment]
Thanks. We'll leave this open until resolved upstream.

**Comment by peter1000** [comment]
Upstream seems to have fixed this very fast: https://github.com/mkdocs/mkdocs/issues/411
