### ISSUE TITLE
Filtering: :typealias

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#45]
I noticed that https://github.com/MichaelHatherly/Lexicon.jl/blob/master/src/filtering.jl#L13 says:
```

* `categories` : categories to include in the result; can include any
  of [:module, :function, :method, :type, :macro, :global, :comment];
```

But at the [Sims.jl - build.jl](https://github.com/tshort/Sims.jl/blob/master/docs/build.jl#L5) there is an additional ** :typealias**.
```
categories = [:comment, :module, :function, :method, :type, :typealias, :macro, :global])
```

Maybe I miss something / or something changed - otherwise I think the docs are incorrect.

**Comment by peter1000** [comment]
Aren't this all valid categories: https://github.com/MichaelHatherly/Docile.jl/blob/master/src/macros.jl#L6

```
object_category(ex) =
    ismethod(ex) ? :method    :
    ismacro(ex)  ? :macro     :
    istype(ex)   ? :type      :
    isalias(ex)  ? :typealias :
    isglobal(ex) ? :global    :
    issymbol(ex) ? :symbol    :
    istuple(ex)  ? :tuple     :
    isvcat(ex)   ? :vcat      :
    isvect(ex)   ? :vect      :
    error("@doc: cannot document object:\n$(ex)")
```

**Comment by MichaelHatherly** [comment]
> Maybe I miss something / or something changed - otherwise I think the docs are incorrect.

Yeah, seems the docs just weren't updated along with the addition of `typealias`.

> Aren't this all valid categories:

The last four, `:symbol` to `:vect`, allow for the special syntax for documenting functions/modules or groups or functions and methods:

```julia
" a function " # `:symbol`
foobar

" a function prior to isn't definition " # `:symbol`
:baz

" a method with argument types Int and Float64 " # `:tuple`
(foobar, Int, Float64)

" two completely different functions " # `:vcat`/`:vect` depending on version 0.3/0.4
[foobar, baz]
```

**Comment by peter1000** [comment]
>  The last four, :symbol to :vect, allow for the special syntax for documenting functions/modules or groups or functions and methods:

this types can not be filtered? or are they translated internally to one of the others?

**Comment by MichaelHatherly** [comment]
They're internal details and get expanded into multiple docstring entries. See [here](https://github.com/MichaelHatherly/Docile.jl/blob/91a469aca0ef2978895802dc310ec7a9e2b31f4d/src/builddocs.jl#L154-L155) and [here](https://github.com/MichaelHatherly/Docile.jl/blob/91a469aca0ef2978895802dc310ec7a9e2b31f4d/src/method-lookup.jl#L315-L342).
