### ISSUE TITLE
Suggestion: add section/page who uses Lexicon/Docile

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#46]
When I was looking for possible julia documentation packages I came across this: [Automatic doc tools for Julia](https://groups.google.com/forum/#!searchin/julia-users/lexicon/julia-users/PJTFLAIOd6g/mOsQlkJuc3oJ) where **tshort** kindly gave some links to his Sims.jl.

I think for new users it will be very helpful to have a list of Pkgs which use Docile/Lexicon for documentation. I would also like to see how others decide on markdown style for Arguments, Return types ect.. - or like Sims.jl [build.jl](https://github.com/tshort/Sims.jl/blob/master/docs/build.jl) is of use.

I would suggest to add a section in the README or anywhere else in the documentation.

e.g. Clang.jl: https://github.com/ihnorton/Clang.jl#users

**Comment by MichaelHatherly** [comment]
Good idea. I think it should be up to the packager whether they'd like to be listed.

A quick grep suggests the following registered packages have, at some point, `REQUIRED` Docile:

```
KNITRO
Diversity
AverageShiftedHistograms
RCall
HttpServer
MDPs
Bootstrap
LMDB
SymPy
BDF
Roots
DataFrames
Lexicon
Weave
Docile
```

It's a bit difficult to locate any unregistered packages (Sims.jl being one of them) though.

**Comment by peter1000** [comment]
> I think it should be up to the packager whether they'd like to be listed.

yes, an section in the readme with a note that they should open an issue if they want to be listed might encourage this.

**Comment by peter1000** [comment]
closed this in favour of https://github.com/MichaelHatherly/Docile.jl/pull/75
