### ISSUE TITLE
Question: option `mathjax` markdown

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#53]
1.
Re-looking through the `md.jl` code I wonder what the option `mathjax` does in the Markdown format.

In `html` it adds the `MathJax.js` in the footer.
https://github.com/MichaelHatherly/Lexicon.jl/blob/master/src/render/html.jl#L167

It seems to me that in Markdown it is just a left over.

Did I miss something? Otherwise we should mention that in the docs.

**Comment by MichaelHatherly** [comment]
Yeah, `mathjax` has no impact on markdown and is just a leftover (or "copyover").

When we change over to a `Config` object (or `Dict{Symbol, Any}`) approach (https://github.com/MichaelHatherly/Lexicon.jl/issues/52) then the `mathjax` setting can just be ignored when not needed.

It will need to remain as an option in the user-facing `save` function though.

**Comment by MichaelHatherly** [comment]
Closed by #56.
