### ISSUE TITLE
Question: mime::MIME

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#54]
there is a lot of just passing around of  mime to distinguish the various `writemime` methods.

I wonder if we could not simplify it and make it shorter/improve readablitiy if we rename the `writemime` for the different outputs.

e.g.
```
writeplain
writehtml
writemd
```

I could do that later in an separate PR

**Comment by MichaelHatherly** [comment]
I've had the same thought several times as well.

The "user-facing" method should definitely remain as a `writemime` method. That's the Julian way to do rich-output using multiple dispatch. The "internal" helper `writemime` methods that relate to specific formats can be changed, and will, as you rightly say, improve readability.

**Comment by peter1000** [comment]
Ok I can also adjust that.

**Comment by peter1000** [comment]
Assuming merge of https://github.com/MichaelHatherly/Lexicon.jl/pull/56 which closes https://github.com/MichaelHatherly/Lexicon.jl/issues/52 and https://github.com/MichaelHatherly/Lexicon.jl/issues/53 I will be looking at this issue before doing the permalink/index thing.

**Comment by peter1000** [comment]
This is quite a bit of work - cause it's difficulte to see where multi dispatching is calling. Have to insert all this `@which` to find out.

**QUESTION:**

It seems to me that in the `md.jl` a couple of functions are just left overs from coping (as you said it is based on html.jl)

e.g.: https://github.com/MichaelHatherly/Lexicon.jl/blob/master/src/render/md.jl#L32
Running save on Lexicon and Docile never calls it: it seems to me it must be handled here: https://github.com/MichaelHatherly/Lexicon.jl/blob/master/src/render/md.jl#L44

I will leave the methods for now but Comment them for the P so if in the future no Problems arise they can be finally removed.

?

**Comment by MichaelHatherly** [comment]
> see where multi dispatching is calling

The `writemime` methods don't call between files and typically call methods further down the files &ndash; if that helps at all.

> e.g.: https://github.com/MichaelHatherly/Lexicon.jl/blob/master/src/render/md.jl#L32
> Running save on Lexicon and Docile never calls it: it seems to me it must be handled here: https://github.com/MichaelHatherly/Lexicon.jl/blob/master/src/render/md.jl#L44

Yes, that appears to be true.

> I will leave the methods for now

Totally fine, I'll have a look at some point to attempt to trim things down a little further. (The `Config` does at least make the signatures more readable.)

**Comment by peter1000** [comment]
Will start the cleanup of the html.jl

**Comment by peter1000** [comment]
Can not find any case where this function is called: 

1.
https://github.com/MichaelHatherly/Lexicon.jl/blob/master/src/render/html.jl#L39

2.
https://github.com/MichaelHatherly/Lexicon.jl/blob/master/src/render/html.jl#L123

**Comment by MichaelHatherly** [comment]
The `Meta{:parameters}` method is used as far as I can tell. The other two can come out a guess.

HTML output isn't a very high priority at the moment, was mostly just a stopgap until the mkdocs / readthedocs was usable. Once we have a nice stable package for doing html generation, probably https://github.com/one-more-minute/Hiccup.jl once it's ready, then we can revisit HTML output more seriously.

**Comment by peter1000** [comment]
Ok I send then just a PR with the cleanup I have made so far.
