### ISSUE TITLE
Comments: last item in file do not work.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#67]
It seems that if a `comment` is the last item in a `.jl` file that it does not work.

**Comment by MichaelHatherly** [comment]
Thanks for finding this.

**Comment by peter1000** [comment]
I will try to find more out about this as I'm looking through Docile now.

**Comment by peter1000** [comment]
I think this is somehow related to https://github.com/JuliaLang/julia/issues/10578.
(But not 100% sure)

**Comment by MichaelHatherly** [comment]
It's to do with this section https://github.com/MichaelHatherly/Docile.jl/blob/f18cff00be79f282ec26d64e37aec1bf80b5830c/src/builddocs.jl#L60-L64. A comment "block" is two args in size, whereas a docstring "block" is three. Comment searching in the leftover args will need to be handled specially I believe.

**Comment by MichaelHatherly** [comment]
Closing, since fixed in https://github.com/MichaelHatherly/Docile.jl/issues/89.
