### ISSUE TITLE
Extract for ALL Pkg documentation

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#71]
I thought it would be nice to be able to auto-generate for all installed Pkgs Api documentation even if they do not explicitly implement Dolice/Lexicon.

e.g.: I have [Lazy.jl](https://github.com/one-more-minute/Lazy.jl) as some requirement installed which does not have any extra docs (except README) and does not use Docile/Lexicon.

But it has a good number of tripple quote docstrings in the src code. e.g. https://github.com/one-more-minute/Lazy.jl/blob/master/src/macros.jl#L37

Also with the julia 0.4 maybe more Pkg will add `@doc` documentation even without using Docile/Lexicon.

Now it would be nice to be able to extract for all (or selected list) the available info - generate for each Pkg in a subfolder the Docile documentation (maybe related Mkdocs .yml file) and maybe a common API-Index without the need to manually inserting:

```julia
using Docile
@document
```

Theoretically one could install ALL 500+ julia pkg and generate a huge indexed API-Documentation (or not so huge because of missing docstrings in most Pkgs ;)

```julia
using Lexicon
generate_pkgs_api(outputroot; pkglist = [])  #empty list means all installed

generate_pkgs_api([Lexicon, Docile, Lazy, SQLite, PicoSAT, NumericExtensions])
```

Do you thing this is feasible and what do you think about the general idea?

**Comment by MichaelHatherly** [comment]
> Also with the julia 0.4 maybe more Pkg will add `@doc` documentation even without using Docile/Lexicon.

Packages using `@doc` but not `using Docile` are the package author's decision. "Auto-patching" packages to import Docile prior to macro-expansion time is unlikely to work I believe. If you've got an idea of how that would work we *could* investigate further.

Plain strings are slightly more realistic, but still have a couple of problems that could block this:

1. `__METADATA__` stores the docstrings *in* the module, which would require `eval`ing that constant into the module after it's been imported. Not something that should really be done as far as I'm concerned. We could move the `__METADATA__` storage out of the module and into a common `Dict` in Docile itself. I've had that thought before, so we might be able to go that route.

2. `@document` redefines the module's `include` function to capture and cache all included paths, not something that's really doable without `eval` from outside of a module. Given the `exec` function and loop-unrolling in `method-lookup.jl` it could be possible to abstractly evaluate each file starting at the root to find all `include`d files that way.

(I'd like to avoid using `eval` at all costs.)

> Do you thing this is feasible and what do you think about the general idea?

*Possibly*, but would require some effort to make sure it doesn't cause side-effects in packages.

**Comment by peter1000** [comment]
see related: [Add experimental code.](https://github.com/MichaelHatherly/Docile.jl/commit/98f64bfc7f14afbd19739c66d669fbc4dfd3fdcf) 

[Experiemental folder[(https://github.com/MichaelHatherly/Docile.jl/tree/master/src/Experimental)

**Comment by MichaelHatherly** [comment]
In progress. Closing in favour of https://github.com/MichaelHatherly/Docile.jl/issues/89.
