### ISSUE TITLE
Docile/Lexicon Light Version

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#73]
This is just some personal ideas.

I only requirement for a documentation package are: 

* it should be quite easy to use and not distract too much from the actual coding while still be easy to adjust output settings.

* I do not need many output formats but one which does the job.

Looking at julia I saw that `markdown` is probably the best things to go with and MkDocs does quite a fine job to produce custom adjustable web pages. (maybe sometimes a julia things will be available like that)

**Point**: I still would like to dedicate some time into documentation before moving on to other julia coding things. I would like to work on a stripped down `DocileLite` version.

* Only ever output format: `markdown`  (so no need to think about dispatching for possible future other formats.

* No support for fancy meta. As you said somewhere a couple of days ago: `markdown` allows doing this in the docstrings. On the otherhand I like some of the docile ideas like 

    - `@doc+`
    - functions 
    - grouped doctrings
   etc.
    - include something like this: https://github.com/MichaelHatherly/Docile.jl/issues/72
   - maybe some other features

* cleanup more code for easier maintanablility in the future

* Integrate Lexicon/DocileLite into one Package (can still leave it as separate modules if needed.

I could do that probably by my own but would prefer to do it under you supervision: you know best what would make sense and also I learn always small things.

Also I would prefer if such project would be hosted together with your other full fledged version. BTW: maybe creating a `Julia documentation pkg` organisation would make sense.

[Edit: quoting macro syntax.]

**Comment by MichaelHatherly** [comment]
> Only ever output format: `markdown` (so no need to think about dispatching for possible future other formats.

Currently Docile defaults to markdown and Lexicon's `save` function works out what format you want by the file extension, so I'm not sure users have to worry about output format much at all.

> No support for fancy meta.

`meta` isn't a huge part of Docile's internals, so I doubt stripping it out would do much to reduce complexity by a noticeable amount.

> cleanup more code for easier maintanablility in the future

Fair enough, further PRs are welcome where you find things worth improving.

> Integrate Lexicon/DocileLite into one Package (can still leave it as separate modules if needed.

This isn't going to happen until package precompilation is in mainline julia. Originally the packages where combined, but loading times were too long and so were split.

**Comment by peter1000** [comment]
thanks for your helpful feedback.
