### ISSUE TITLE
Save index in same order as modules.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#90]
currently the index reference is in the order as one pushes them to Index().

Probably it should be sorted as the general dcoumentation - or make it an option -but than the general module order should also be an option.

**Comment by MichaelHatherly** [comment]
> currently the index reference is in the order as one pushes them to Index().

That behaviour is alright for the moment. Options for changing it would be nice to have though.

**Comment by peter1000** [comment]
I was mistaken because I looked at the final oder of the modules which where produced by MkDocs and defined in the `mkdocs.yml` ;)

Anyway leave this open for now.

**Comment by MichaelHatherly** [comment]
Closing since we're moving away from ``Index`` in favour of ``document(...)``.
