### ISSUE TITLE
Add Anchor to groups like Exported/Internal.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#92]
this should not be too hard and one can link internally the Api-Index - also maybe helpful when style is not one of the h1-6.

**Comment by MichaelHatherly** [comment]
:+1:

**Comment by peter1000** [comment]
I can do that later or tomorrow

**Comment by peter1000** [comment]
If possible add an anchor to Exported/Internal, all groups of types even if they are not displayed. This would allow referencing it internally: These are also stable names and do not change.

Exception: one might get a dead link if some groups are filtered and skipped e.g.

a.md references in a docstring:
```

"""
[see section](#modulename_types)
"""
```
but in a custom saving one uses a setup without types.
```
save("docs/api/Lexicon.md", Lexicon; category_order = [:method, :macro]);
```

Gets also messy if a other module is referenced (which involves relative path) and that the saving path is changed.

Anyway might still be worthy at least in a forum one could post a link to a section in a nice way.

**Comment by peter1000** [comment]
Adding permalinks to the section groups will show up in the side panel - not sure if one can do something about that without changing the mkdocs theme.
![screenshot from 2015-04-26 23-46-22](https://cloud.githubusercontent.com/assets/6168860/7340928/ec1b00fc-ec6e-11e4-8ebf-8f771a13b32e.png)

**Comment by peter1000** [comment]
In the new Docile (julia 0.4/0.5) not anymore relevant.
