### ISSUE TITLE
Placement of "[Exported]" text.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#93]
> MichaelHatherly: (Only nitpick would be the placement of "[Exported]" and "[Internal]" labels (they're controlled by the :md_subheader setting right?), but that's really a stylistic issue and won't hold up merging of this.)  https://github.com/MichaelHatherly/Lexicon.jl/pull/89#issuecomment-96392918

>  (they're controlled by the :md_subheader setting right?)

I thought for bigger projects it might be better to group by category headers and not simple by 'Exported' / 'Internal'.

![screenshot from 2015-04-26 14-30-34](https://cloud.githubusercontent.com/assets/6168860/7338404/3f239406-ec21-11e4-933d-a908e41f0086.png)

Do you prefer to have all (exported and internal) below one catecory header and  "[Exported]" and "[Internal]" next to the catecory removed?

**Comment by MichaelHatherly** [comment]
> I thought for bigger projects it might be better to group by category headers

Yeah, that sounds better.

> Do you prefer to have all (exported and internal) below one catecory header and "[Exported]" and "[Internal]" next to the catecory removed?

I've not got a preference at the moment. Once these have been around for a bit I should have a better idea.

**Comment by peter1000** [comment]
* `md_subheader`           (default: `:simple`): Valid options are ":skip, :simple, :category"

    * `md_subheader=:simple`   adds documentation and *API-Index* subheaders "Exported" / "Internal".
    * `md_subheader=:category` adds documentation and *API-Index* subheaders per category.
    * `md_subheader=:skip`     adds no subheaders to the documentation and *API-Index* and can be used
    for documentation which has only few entries.

**Comment by peter1000** [comment]
added a new `md_subheader` option `split_category`

 * `md_subheader=:simple`   adds documentation and *API-Index* subheaders "Exported" / "Internal".

* `md_subheader=:category` adds documentation and *API-Index* subheaders per category.

* `md_subheader=:split_category` adds documentation and *API-Index* subheaders per category. Each categort is split into: `category ["Exported"]` and `category ["Internal"]`

* `md_subheader=:skip`     adds no subheaders to the documentation and *API-Index* and can be used for documentation which has only few entries.

---

**To be discussed**: `md_subheader=:split_category` would it be better to put the 'Exported' in front.

### Exported Methods
### Exported Types
### Internal Methods
### Internal Types

instead of current

### Methods [Exported]
### Types [Exported]
### Methods [Internal]
### Types [Internal]

Any preference? Not sure if it worthy to add for this a new Config field

**Comment by peter1000** [comment]
I guess this should be changed: just use simple types without anything in fron or after and insert the "External" - "Internal" subheaders. Probably one wants  to allow separate styling in such case: e.g. "External" - "Internal" H3  and the Category subheader something like H4

---


### Exported 

#### Methods
#### Types

### Internal
#### Methods
#### Types

**Comment by peter1000** [comment]
I will do that.

**Comment by MichaelHatherly** [comment]
:+1: to that last example of yours @peter1000. Much clearer looking.

**Comment by peter1000** [comment]
I nearly finished this : but than started cleaning up the Config and had the idea with the signature -- Well today I start looking into Docile - not easy as an outsider ;)

But I think I'm getting around and a bit of your help I should be able to finishe most of the planned things in the next couple of days. I will send tomorrow morning a Docile PR for the adding of the signature to entry.data

**Comment by MichaelHatherly** [comment]
> not easy as an outsider ;)

Especially with a mutually recursive call across different files :) (the `loopdocs` code, don't worry too much about it though, it's off by default and I haven't found much use for it actually.)

> a bit of your help

Feel free to ask about anything regarding Docile, I should be around more from now through the weekend.

**Comment by peter1000** [comment]
I think this could be closed with the new `document(...)`
