### ISSUE TITLE
Shortcomings of new reference anchors.

### ISSUE THREAD

**Issue by peter1000** [MichaelHatherly/Lexicon.jl#95]
Writing documentation to refer internally to an other method ect. is still very messy.

Reason: anchor names are autogenerated which means if new methods with similar name are added the anchor name might change?

The option to produce permanent similar names based on the whole signature might be not the best eighter. (very long messy anchornames)

Option I can think of:

* simplest solution: add for the few cases one refers internally a manual html anchor/reference.

* Docile meta might provide such option

**Comment by MichaelHatherly** [comment]
Yeah, I'm not sure what the best move will be here... over the next week we can iron out the wrinkles.

**Comment by peter1000** [comment]
> Writing documentation to refer internally to an other method ect. is still very messy.
>
> Reason: anchor names are autogenerated which means if new methods with similar name are added the anchor name might change?

I had an idea: how we can solve this:  issue `Propose new page meta` #103 allows adding of exact oder numbers in a Section for each obj.

so if we generate the anchor with example: this numbers they should stay unique and are thus permanently referable.

**Comment by peter1000** [comment]
If needed this can be reopened later. but with the new  `document(...)` the `!!section` meta syntax seems to be not relevant as I had first planned it to be.
